import { stockByTicker } from "./stocks";

export type Venue = "morpho" | "aave" | "uniswap";

export type Market = {
  id: string;
  venue: Venue;
  /** Card headline, clutch-style collection name. */
  name: string;
  ticker: string;
  /** Display token for the market (stock or LP share). */
  token: string;
  tokenColor: string;
  apr: number;
  pricePer: number;
  priceUnit: string;
  vol24h: number;
  utilization: number;
  utilNum: number;
  utilDen: number;
  supply: number;
  feesToFolio: number;
  verified: boolean;
  liqLocked: boolean;
  special: boolean;
  hot: boolean;
  status: "queued" | "live";
  blurb: string;
};

/**
 * Yield venues Circle / Arc posted about ahead of Sept 16:
 * Uniswap on Arc (Aug 17), Morpho Midnight (Aug 26 / Sep 3), Aave V4 (Sep 8–10).
 * Cards are the clutch/anvil market format, pointed at tokenized stocks instead of NFTs.
 */
export const MARKETS: Market[] = [
  {
    id: "morpho-crcl",
    venue: "morpho",
    name: "Circle Isolated",
    ticker: "CRCL",
    token: "CRCL",
    tokenColor: "#c8f542",
    apr: 22.8,
    pricePer: 124,
    priceUnit: "USDC",
    vol24h: 1_140_000,
    utilization: 61,
    utilNum: 2720,
    utilDen: 4444,
    supply: 4_444_000,
    feesToFolio: 82_400,
    verified: true,
    liqLocked: true,
    special: true,
    hot: true,
    status: "queued",
    blurb: "Morpho isolated market. Supply CRCL, borrow USDC. Fees skim back to the folio keeper.",
  },
  {
    id: "morpho-nvda",
    venue: "morpho",
    name: "Hopper Credit",
    ticker: "NVDA",
    token: "NVDA",
    tokenColor: "#76e1ff",
    apr: 18.1,
    pricePer: 218.29,
    priceUnit: "USDC",
    vol24h: 2_410_000,
    utilization: 74,
    utilNum: 3288,
    utilDen: 4444,
    supply: 2_200_000,
    feesToFolio: 141_000,
    verified: true,
    liqLocked: true,
    special: true,
    hot: true,
    status: "queued",
    blurb: "Morpho isolated NVDA/USDC. High utilisation, fixed-term Midnight quotes when they list.",
  },
  {
    id: "morpho-aapl",
    venue: "morpho",
    name: "Cupertino Vault",
    ticker: "AAPL",
    token: "AAPL",
    tokenColor: "#c8f542",
    apr: 12.4,
    pricePer: 332.52,
    priceUnit: "USDC",
    vol24h: 890_000,
    utilization: 53,
    utilNum: 2627,
    utilDen: 5000,
    supply: 3_100_000,
    feesToFolio: 64_200,
    verified: true,
    liqLocked: true,
    special: true,
    hot: false,
    status: "queued",
    blurb: "Supply distributed AAPL as collateral. Borrow USDC against it on Morpho.",
  },
  {
    id: "aave-usdc",
    venue: "aave",
    name: "Arc Core Hub",
    ticker: "USDC",
    token: "USDC",
    tokenColor: "#2775ca",
    apr: 4.82,
    pricePer: 1,
    priceUnit: "USDC",
    vol24h: 6_200_000,
    utilization: 41,
    utilNum: 1820,
    utilDen: 4444,
    supply: 18_400_000,
    feesToFolio: 29_800,
    verified: true,
    liqLocked: false,
    special: false,
    hot: false,
    status: "queued",
    blurb: "Aave V4 core hub on Arc. USDC lenders. Posted by @arc Sep 8–10.",
  },
  {
    id: "aave-aapl",
    venue: "aave",
    name: "Tokenized Spoke",
    ticker: "AAPL",
    token: "aAAPL",
    tokenColor: "#b4ff39",
    apr: 9.2,
    pricePer: 332.52,
    priceUnit: "USDC",
    vol24h: 410_000,
    utilization: 17,
    utilNum: 759,
    utilDen: 4444,
    supply: 1_880_000,
    feesToFolio: 11_400,
    verified: true,
    liqLocked: false,
    special: false,
    hot: false,
    status: "queued",
    blurb: "Aave V4 tokenized spoke — supply-only wrapper so distributed stocks can sit in the hub without extra borrow risk.",
  },
  {
    id: "uni-crcl",
    venue: "uniswap",
    name: "Circle LP",
    ticker: "CRCL",
    token: "CRCL",
    tokenColor: "#c8f542",
    apr: 41.8,
    pricePer: 124,
    priceUnit: "USDC",
    vol24h: 3_200_000,
    utilization: 68,
    utilNum: 3011,
    utilDen: 4444,
    supply: 5_200_000,
    feesToFolio: 190_600,
    verified: true,
    liqLocked: true,
    special: true,
    hot: true,
    status: "queued",
    blurb: "Uniswap V3 CRCL/USDC 1% — the same venue eve.fun Instant already uses. LP fees, plus a skim to the folio.",
  },
  {
    id: "uni-nvda",
    venue: "uniswap",
    name: "Hopper Pool",
    ticker: "NVDA",
    token: "NVDA",
    tokenColor: "#7cff6b",
    apr: 28.4,
    pricePer: 218.29,
    priceUnit: "USDC",
    vol24h: 1_840_000,
    utilization: 52,
    utilNum: 2302,
    utilDen: 4444,
    supply: 2_222_000,
    feesToFolio: 99_400,
    verified: true,
    liqLocked: true,
    special: true,
    hot: true,
    status: "queued",
    blurb: "Uniswap V3 NVDA/USDC. Tight execution on a USDC-gas chain, as @arc framed it Aug 17.",
  },
  {
    id: "uni-spy",
    venue: "uniswap",
    name: "Index Pool",
    ticker: "SPY",
    token: "SPY",
    tokenColor: "#6ee7ff",
    apr: 14.2,
    pricePer: 770.25,
    priceUnit: "USDC",
    vol24h: 620_000,
    utilization: 38,
    utilNum: 1688,
    utilDen: 4444,
    supply: 880_000,
    feesToFolio: 22_100,
    verified: true,
    liqLocked: true,
    special: false,
    hot: false,
    status: "queued",
    blurb: "SPY/USDC on Uniswap. Broad book for holders who want index exposure working overnight.",
  },
  {
    id: "morpho-tsla",
    venue: "morpho",
    name: "Midnight TSLA",
    ticker: "TSLA",
    token: "TSLA",
    tokenColor: "#ff6b6b",
    apr: 8.6,
    pricePer: 367.6,
    priceUnit: "USDC",
    vol24h: 540_000,
    utilization: 29,
    utilNum: 1290,
    utilDen: 4444,
    supply: 1_100_000,
    feesToFolio: 18_700,
    verified: true,
    liqLocked: true,
    special: false,
    hot: false,
    status: "queued",
    blurb: "Morpho Midnight — fixed-rate, fixed-term lending against TSLA. Arc x Morpho session Sep 3.",
  },
  {
    id: "aave-buidl",
    venue: "aave",
    name: "T-bill Sleeve",
    ticker: "BUIDL",
    token: "BUIDL",
    tokenColor: "#e2e8d8",
    apr: 5.14,
    pricePer: 1,
    priceUnit: "USDC",
    vol24h: 210_000,
    utilization: 22,
    utilNum: 980,
    utilDen: 4444,
    supply: 6_400_000,
    feesToFolio: 8_200,
    verified: true,
    liqLocked: false,
    special: false,
    hot: false,
    status: "queued",
    blurb: "BlackRock BUIDL as Aave collateral once it lists on Arc. Cash sleeve of the folio.",
  },
  {
    id: "morpho-usyc",
    venue: "morpho",
    name: "Hashnote Credit",
    ticker: "USYC",
    token: "USYC",
    tokenColor: "#b8a6ff",
    apr: 6.05,
    pricePer: 1,
    priceUnit: "USDC",
    vol24h: 330_000,
    utilization: 34,
    utilNum: 1510,
    utilDen: 4444,
    supply: 3_300_000,
    feesToFolio: 14_600,
    verified: true,
    liqLocked: true,
    special: false,
    hot: false,
    status: "queued",
    blurb: "USYC isolated market. Circle-adjacent T-bill yield, Morpho utilisation.",
  },
  {
    id: "uni-aapl",
    venue: "uniswap",
    name: "Cupertino LP",
    ticker: "AAPL",
    token: "AAPL",
    tokenColor: "#d4d4d4",
    apr: 19.7,
    pricePer: 332.52,
    priceUnit: "USDC",
    vol24h: 1_020_000,
    utilization: 47,
    utilNum: 2088,
    utilDen: 4444,
    supply: 1_640_000,
    feesToFolio: 44_000,
    verified: true,
    liqLocked: true,
    special: true,
    hot: false,
    status: "queued",
    blurb: "AAPL/USDC Uniswap V3. Deposit distributed Apple, earn the 1% fee tier.",
  },
];

export function marketStock(m: Market) {
  return stockByTicker[m.ticker];
}

export const VENUE_META: Record<
  Venue,
  { label: string; x: string; posted: string }
> = {
  morpho: {
    label: "Morpho",
    x: "@Morpho",
    posted: "Arc x Morpho · Aug 26 / Sep 3",
  },
  aave: {
    label: "Aave V4",
    x: "@aave",
    posted: "Arc x Aave · Sep 8–10",
  },
  uniswap: {
    label: "Uniswap",
    x: "@Uniswap",
    posted: "Uniswap on Arc · Aug 17",
  },
};
